### ISSUE TITLE
Add reaction selection to the Story Board node

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/Tales#137]
Add a list of reactions to the objects that are available to drag to the Story Board Node:
- Node - Add support for a reaction
- Reactions - Show them in pose mode and animate them on mouse over

**Comment by DuarteFGuerreiro** [comment]
![Image](https://github.com/duquevieira/Tales/assets/72998351/136e2d62-1e8a-45c0-9221-e48d2ae74c63)
