### ISSUE TITLE
Add micro-interaction to objects

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/Tales#138]
Add a property for the animation of the object that represents it's micro interaction when manipulated by the player:
- Game Engine - The engine plays the micro interaction when clicked
- Example - Drawers, lamps,...

**Comment by DuarteFGuerreiro** [comment]
![Image](https://github.com/duquevieira/Tales/assets/72998351/5f988f0a-8853-4102-baaa-1333a5ffa38a)
