### ISSUE TITLE
Enable user to select a story and go into play mode

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/Tales#14]

**Comment by Daniel-Gavinho** [comment]
![Image](https://user-images.githubusercontent.com/113610235/226888882-95d6ef6f-0f98-4c38-b23d-78a980cebe2c.png)


![Image](https://user-images.githubusercontent.com/113610235/226888938-17cdf3f7-30b7-4fe9-8bd7-2bd45b58ff2e.png)
