### ISSUE TITLE
Add life to rooms

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/Tales#140]
Add living beings to the rooms as props:
- Animation - Add animations to the object
- Example - Cats, dogs, Plants (wiggling), people

**Comment by DuarteFGuerreiro** [comment]
![Image](https://github.com/duquevieira/Tales/assets/72998351/d024d610-a810-4886-a6ab-06d7f6df023f)



![Image](https://github.com/duquevieira/Tales/assets/72998351/dfcfaa0b-dec9-430e-bffa-3edd57e94973)
