### ISSUE TITLE
Classify base objects

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/Tales#3]

**Comment by andreauxtero** [comment]
![Image](https://user-images.githubusercontent.com/61872583/226893987-fdfbffe0-c385-46ca-8656-bac7cbcbedd4.png)
![Image](https://user-images.githubusercontent.com/61872583/226893989-7ae2b23e-6382-4fd0-9711-06904a1a1b68.png)
![Image](https://user-images.githubusercontent.com/61872583/226893990-3137e4f8-b670-4185-ade0-a0f5daa86329.png)
![Image](https://user-images.githubusercontent.com/61872583/226893988-f9ece7c3-796e-4dc1-b358-df692cc89e25.png)
