### ISSUE TITLE
Add support for several classes of objects allowed next to a given object class

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/Tales#36]

**Comment by andreauxtero** [comment]
![Image](https://user-images.githubusercontent.com/61872583/228505126-fc6339cf-cb3f-48fc-947a-3368813e1c6b.png)
![Image](https://user-images.githubusercontent.com/61872583/228505128-d8ce4c53-5d84-4949-b2fe-7c132fe2fe3a.png)
![Image](https://user-images.githubusercontent.com/61872583/228505127-bfbac25e-6bc7-4146-bae3-c271750bed56.png)
![Image](https://user-images.githubusercontent.com/61872583/228505129-ff10635a-aa90-46c0-8975-4a594c28d9b1.png)
