### ISSUE TITLE
Re-arrange the menus to portray clear and simple options

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/Tales#56]
Main menu:
- Play
- Create
- Tales
- Quit

Room
- Continue
- Quit

Auto-save the playing data from time to time (every minute?).

**Comment by Daniel-Gavinho** [comment]
![Image](https://github.com/duquevieira/Tales/assets/113610235/1ccdbe44-b6e6-48e2-bd04-68b79b9b52e2)
