### ISSUE TITLE
Save and load Tales

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/Tales#65]
1. Create the tale structure from a loaded tale.
2. Save a tale structure in json to a file.

**Comment by andreauxtero** [comment]
![Image](https://github.com/duquevieira/Tales/assets/61872583/2308c6a5-c0cc-43f9-8c31-b4b62948b374)



![Image](https://github.com/duquevieira/Tales/assets/61872583/6acb1dd8-d4b2-4d57-a091-21c9794bc76a)
