### ISSUE TITLE
Create the storyboard from the tale definition

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/Tales#69]
From the tale class, generate the UI of the storyboard:
- Create the storyboard by spawning the nodes and connectors of the storyboard

**Comment by DuarteFGuerreiro** [comment]
História criada no editor:

![Image](https://github.com/duquevieira/Tales/assets/72998351/45f7f9de-463e-475d-bcf5-6e22f10dc214)

História depois de gravada e recarregada:

![Image](https://github.com/duquevieira/Tales/assets/72998351/209e1d84-4059-4b49-a7bd-c37fc204ac95)
