### ISSUE TITLE
Create the game definition

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/Tales#71]
Create the class that represents a game (similar to the tale class):
- Add a reference to the id of the tale being played
- Add the position of the character
- Add the inventory 
- Storyboard completion

**Comment by Daniel-Gavinho** [comment]
{
    "id": "63576297-97a1-4b79-8de9-c728219745eb",
    "tenantId": "8cddde22-bd7d-4af9-8a2c-ceac14a35eae",
    "name": "Game",
    "pluralName": "Games",
    "jsonSchema": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "description": "Current game state",
        "properties": {
            "Player": {
                "type": "object",
                "description": "Current player position",
                "properties": {
                    "_row": {
                        "type": "number"
                    },
                    "_column": {
                        "type": "number"
                    }
                }
            },
            "Storyboard": {
                "type": "array",
                "description": "The current Storyboard",
                "items": {
                    "type": "object",
                    "properties": {
                        "Id": {
                            "type": "string"
                        },
                        "ColliderName": {
                            "type": "string"
                        },
                        "Requirements": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "_itemName": {
                                        "type": "string"
                                    },
                                    "_amount": {
                                        "type": "number"
                                    }
                                }
                            }
                        },
                        "Acquired": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "_itemName": {
                                        "type": "string"
                                    },
                                    "_amount": {
                                        "type": "integer"
                                    }
                                }
                            }
                        },
                        "StepCoordinates": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        }
    }
