### ISSUE TITLE
Add toggle menu option to switch between Story Board, Test and Room in Creation mode

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/Tales#76]
In the Creation mode, there are 3 editable states:
- Story Board - Where the creator arranges the story board
- Room - Where the creator arranges the room and places objects and the characters
- Test - Where the tale is tested

Add three menu buttons to switch between these modes:
- Highlight the current mode
- Have a variable (enumerable) with the current state
- Use the variable as the condition on every component (to disable or gray out)

**Comment by andreauxtero** [comment]
https://github.com/duquevieira/Tales/assets/61872583/970cb321-ee2f-46f3-a0ec-9075322615d3
