### ISSUE TITLE
Add colliders sensors to the objects to handle interaction

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/Tales#8]
Add colliding info to the objects placed in the play mode:
- Add the colliders to the placed objects, based on their definition
- Provide an event for the game engine to interact with the storyboard

**Comment by DuarteFGuerreiro** [comment]
![Image](https://user-images.githubusercontent.com/72998351/224506567-8b32bb02-3252-4f5e-9e84-1f709a6650b1.png)
