### ISSUE TITLE
Use endpoints and schema to save and load games and tales

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/Tales#82]
Create schema for game and tale:
- Game
   - Name
   - Version
   - Tale
   - World
   - Inventory 
   - Character

- Tale
   - Name
   - Version
   - World
   - Storyboard
   - Character

Site
https://web.orangesmoke-c07594bb.westeurope.azurecontainerapps.io/8cddde22-bd7d-4af9-8a2c-ceac14a35eae/SystemPackage/ListPackages

Tenant
8cddde22-bd7d-4af9-8a2c-ceac14a35eae

**Comment by Daniel-Gavinho** [comment]
![Image](https://github.com/duquevieira/Tales/assets/113610235/3f438c5b-4d4a-4f07-8eb9-d77ab513531a)

**Comment by Daniel-Gavinho** [comment]
![Image](https://github.com/duquevieira/Tales/assets/113610235/f5dcc471-20ce-4fcf-bcfe-ae81ec5b1ef0)
