### ISSUE TITLE
Add and remove items from the inventory in game mode

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/Tales#83]
While playing the game, when the player picks up items or uses them:
- Add and remove items from the inventory
- The game engine has to be aware of the items in the inventory
- The inventory has to have an in memory representation (class)

**Comment by DuarteFGuerreiro** [comment]
https://github.com/duquevieira/Tales/assets/72998351/02a08663-e57a-46f5-bba6-ff307c22a8b4
